---
title: Jana Pauls Ministries Intl.
timezone: UTC
collections:
  devotionals:
    title: Devotionals
    output: true
  media:
    title: Media
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    subtitle: ''
    image: ''
    tags:
    - none
- scope:
    path: ''
    type: pages
  values:
    layout: pages
    title: ''
    subtitle: ''
    image: ''
    navigation_weight: 
- scope:
    path: ''
    type: media
  values:
    layout: media
    image: 
    video_id:
    - none
    audio_id:
    - none
    verses:
    - none
- scope:
    path: ''
    type: devotionals
  values:
    layout: devotionals
    title: ''
    subtitle: ''
    image: ''
    tags:
    - none
    verses:
    - none
description: Follow what God is doing in the nations through one surrendered life.
about:
  image: "/uploads/IMG_0005.jpg"
  subtitle: Serving the kingdom daily!
  text: "Jana left her former home Germany straight out of school at the age of 19
    to study the Bible full time for 3 years at the River Bible Institute in Tampa
    Florida. After experiencing the baptism in the fire of God that John the Baptist
    talked about in Luke 3:16, her life was changed for ever.\n\"I heard the cry of
    the nations on the inside of me and it shook me to my core. Words cannot describe
    what it felt like. All I know is that I have to reach the lost with the life changing
    message and saving power of the Gospel of Jesus Christ and carry that fire into
    the churches to see revival. Especially in places where no one wants to go. Until
    the whole world knows Jesus is Lord.\"\n\nMissionary and Evangelist Jana Pauls
    has been in the full time ministry since graduating Bible School in 2010 traveling
    internationally to preach and teach the Word of God and train and mobilize believers
    to bring in the harvest of souls. \nShe has ministered in America, Europe, Africa
    and the Middle East in a total of 21 nations so far and counting."
slideshow-images:
- "/uploads/IMG_0222.jpg"
- uploads/0e22d094-85d5-48a8-8dad-48499f09d3f2.png
- uploads/c30bb026-9a6e-4b54-aa56-8fe80c3ac04f.jpg
social:
  name: Jana Pauls
  links:
  - https://twitter.com/gerssian
  - https://www.facebook.com/gerssian
  - https://instagram.com/gerssian
  - https://instagram.com/janapauls
email: gerssian@gmail.com
contact:
  subtitle: I would love to hear from you!
  text: I will get back to you as soon as I can.
give:
  subtitle: Support The Mission
  text: If you would like to be a part of what the Lord is doing you can sow a seed
    online.
baseurl: 
url: https://janapauls.com
permalink: none
twitter:
  username: gerssian
gems:
- jekyll-feed
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: css/_sass
  style: uncompressed
ga_analytics: UA-71688221-6
markdown: kramdown
kramdown:
  imput: GFM
