---
title: Jana Pauls Ministries Intl.
timezone: UTC
collections:
  devotionals:
    title: Devotionals
    output: true
  media:
    title: Media
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    subtitle: ''
    image: ''
    tags:
    - none
- scope:
    path: ''
    type: pages
  values:
    layout: pages
    title: ''
    subtitle: ''
    image: ''
    navigation_weight: 
- scope:
    path: ''
    type: media
  values:
    layout: media
    image: 
    video_id:
    - none
    audio_id:
    - none
    verses:
    - none
- scope:
    path: ''
    type: devotionals
  values:
    layout: devotionals
    title: ''
    subtitle: ''
    image: ''
    tags:
    - none
    verses:
    - none
description: Follow what God is doing in the nations through one surrendered life.
about:
  image: 'uploads/0e22d094-85d5-48a8-8dad-48499f09d3f2.png'
  subtitle: Serving the kingdom daily!
  text: This is the about me paragraph!
slideshow-images:
  - 'uploads/received_1450670428279037.jpeg'
  - 'uploads/0e22d094-85d5-48a8-8dad-48499f09d3f2.png'
  - 'uploads/c30bb026-9a6e-4b54-aa56-8fe80c3ac04f.jpg'
social:
  name: Jana Pauls
  links:
  - https://twitter.com/gerssian
  - https://www.facebook.com/gerssian
  - https://instagram.com/gerssian
  - https://instagram.com/janapauls
email: gerssian@gmail.com
contact:
  subtitle: I can't wait to hear from you!
  text: I'll try to get back to you as soon as I can.
give:
  subtitle: Support The Mission
  text: If you would like to be a part of what the Lord is doing you can sow a seed
    online.
baseurl: 
url: https://janapauls.com
permalink: none
twitter:
  username: gerssian
gems:
- jekyll-feed
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: css/_sass
  style: uncompressed
ga_analytics: UA-71688221-6
markdown: kramdown
kramdown:
  imput: GFM
