---
title: "\U0001F525 Jana Pauls Ministries Intl."
timezone: UTC
collections:
  media:
    title: Media
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    subtitle: ''
    image: ''
    tags:
    - ''
- scope:
    path: ''
    type: pages
  values:
    layout: pages
    title: ''
    subtitle: ''
    image: ''
    navigation_weight: 
- scope:
    path: ''
    type: media
  values:
    layout: media
    image: 
    video_id:
    - none
    audio_id:
    - none
    verses:
    - none
description: Follow what God is doing in the nations through one surrendered life.
email: gerssian@gmail.com
baseurl: 
url: https://janapauls.com
permalink: none
twitter:
  username: gerssian
social:
  name: Jana Pauls
  links:
  - https://twitter.com/gerssian
  - https://www.facebook.com/gerssian
  - https://instagram.com/gerssian
  - https://instagram.com/janapauls
gems:
- jekyll-feed
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: css/_sass
  style: uncompressed
ga_analytics: UA-71688221-6
markdown: kramdown
kramdown:
  imput: GFM
about:
  image: "/uploads/097d1fd7-9e58-451b-b44a-380820836096.jpg"
  subtitle: Serving the kingdom daily!
  text: This is the about me paragraph!
contact:
  subtitle: I can't wait to hear from you!
  text: I'll try to get back to you as soon as I can.
give:
  subtitle: Support The Mission
  text: If you would like to be a part of what the Lord is doing you can sow a seed
    online.
