---
title: Jana Pauls Ministries Intl.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    subtitle: ''
    image: ''
    tags:
    - ''
- scope:
    path: ''
    type: page
  values:
    layout: page
    title: ''
    subtitle: ''
    image: ''
description: Follow what God is doing in the nations through one surrendered life.
email: gerssian@gmail.com
baseurl: 
url: https://janapauls.com
permalink: none
twitter:
  username: gerssian
social:
  name: Jana Pauls
  links:
  - https://twitter.com/gerssian
  - https://www.facebook.com/gerssian
  - https://instagram.com/gerssian
  - https://instagram.com/janapauls
gems:
- jekyll-feed
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
repository: me/super-cool-project
sass:
  sass_dir: css/_sass
  style: compressed
ga_analytics: 
markdown: kramdown
kramdown:
  imput: GFM
about:
  image: "/uploads/download.jpg"
  subtitle: Serving the kingdom daily!
  text: This is the about me paragraph!
contact:
  subtitle: I can't wait to hear from you!
  text: I'll try to get back to you as soon as I can.
