---
title: Jana Pauls Ministries Intl.
timezone: UTC
collections:
  devotionals:
    title: Devotionals
    output: true
  media:
    title: Media
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    subtitle: ''
    image: ''
    tags:
    - none
- scope:
    path: ''
    type: pages
  values:
    layout: pages
    title: ''
    subtitle: ''
    image: ''
    navigation_weight: 
- scope:
    path: ''
    type: media
  values:
    layout: media
    image: 
    subtitle: 
    video_id:
    - none
- scope:
    path: ''
    type: devotionals
  values:
    layout: devotionals
    title: ''
    subtitle: ''
    image: ''
    tags:
    - none
    verses:
    - none
description: |-
  PREACHING THE GOSPEL OF JESUS CHRIST WITH POWER TO SEE SOULS SAVED AND LIVES TRANSFORMED IN THE NATIONS OF THE WORLD.
  The mission: REVIVAL.
about:
  image: "/uploads/IMG_0005.jpg"
  subtitle: Expanding God's kingdom daily.
  text: 
devotionals:
  image: "/uploads/map%20and%20compass.jpeg"
slideshow-images:
- "/uploads/IMG_3491.jpg"
- "/uploads/fullsizeoutput_30c4.jpeg"
- "/uploads/IMG_0004.jpg"
- "/uploads/IMG_1192.jpg"
social:
  name: Jana Pauls
  links:
  - https://twitter.com/gerssian
  - https://www.facebook.com/gerssian
  - https://instagram.com/janapauls
email: missionary.janapauls@gmail.com
contact:
  subtitle: I would love to hear from you <3
  text: "...unless you want to tell me something really flaky, please don't ;)"
baseurl: 
url: https://janapauls.com
permalink: none
twitter:
  username: gerssian
paypal: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=BRMY9EMVUS2NU
counter:
  souls: 52529
  countries: 33
  cities: 86
plugins:
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: css/_sass
  style: uncompressed
ga_analytics: UA-98019281-1
markdown: kramdown
kramdown:
  imput: GFM
