---
title: Jana Pauls Ministries Intl.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
description: An evangelist helping save the world one soul at a time
email: gerssian@gmail.com
baseurl: ''
url: https://janapauls.com
permalink: none
twitter:
  username: gerssian
social:
  name: Jana Pauls
  links:
  - https://twitter.com/gerssian
  - https://www.facebook.com/gerssian
  - https://instagram.com/gerssian
  - https://instagram.com/janapauls
markdown: kramdown
kramdown:
  imput: GFM
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Collection Configs
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
    title: ""
    subtitle: ""
    image: ""
    tags: 
      - ""
- scope:
    path: ""
    type: pages
  values:
    layout: pages
    title: ""
    subtitle: ""
    image: ""
- jekyll-feed
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
