---
title: Jana Pauls Ministries Intl.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    subtitle: ''
    image: ''
    tags:
    - ''
- scope:
    path: ''
    type: pages
  values:
    layout: pages
    title: ''
    subtitle: ''
    image: ''
description: Helping save the world one soul at a time.
email: gerssian@gmail.com
baseurl: 
url: https://janapauls.com
permalink: none
twitter:
  username: gerssian
social:
  name: Jana Pauls
  links:
  - https://twitter.com/gerssian
  - https://www.facebook.com/gerssian
  - https://instagram.com/gerssian
  - https://instagram.com/janapauls
gems:
- github-pages
- jekyll-seo-tag
- jekyll-github-metadata
repository: me/super-cool-project
sass:
  sass_dir: css/_sass
  style: compressed
ga_analytics: 
markdown: kramdown
kramdown:
  imput: GFM
